# Generated by Django 3.0.3 on 2021-01-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210104_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264, unique=True)),
                ('Last_name', models.CharField(max_length=264, unique=True)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
